// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLeT2Zf0Z6MnzZiytlwECRRbksyjBiL7U',
    appId: '1:110232948737:web:1da9c0d626d7c818df7000',
    messagingSenderId: '110232948737',
    projectId: 'gitactionfirebasedistribution',
    authDomain: 'gitactionfirebasedistribution.firebaseapp.com',
    storageBucket: 'gitactionfirebasedistribution.appspot.com',
    measurementId: 'G-PDE8ZEQ7DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo8U9iIR6NJ87tDMd4jpPFa_Bdj_yJ1RQ',
    appId: '1:110232948737:android:dfd8384d0cf07240df7000',
    messagingSenderId: '110232948737',
    projectId: 'gitactionfirebasedistribution',
    storageBucket: 'gitactionfirebasedistribution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOytFv8hwWiGIfVQvXMDn9nwE0EVCdkmI',
    appId: '1:110232948737:ios:30e44c061add0973df7000',
    messagingSenderId: '110232948737',
    projectId: 'gitactionfirebasedistribution',
    storageBucket: 'gitactionfirebasedistribution.appspot.com',
    iosBundleId: 'com.example.sampleexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOytFv8hwWiGIfVQvXMDn9nwE0EVCdkmI',
    appId: '1:110232948737:ios:da2b145120433ba8df7000',
    messagingSenderId: '110232948737',
    projectId: 'gitactionfirebasedistribution',
    storageBucket: 'gitactionfirebasedistribution.appspot.com',
    iosBundleId: 'com.example.sampleexample.RunnerTests',
  );
}
